import Head from 'next/head'
import Navbar from '../components/navbar'
import Navbar2 from '../components/navbar2';
import Hero from '../components/hero'
import Arrivals from '../components/arrivals';
import Footer from '../components/footer';
import { useEffect, useState } from "react";

export default function Home() {
  const [colorChange, setColorchange] = useState(false);
  const changeNavbarColor = () => {
    if (window.scrollY >= 80) {
      setColorchange(true);
    } else {
      setColorchange(false);
    }
  };
  useEffect(() => {
    window.addEventListener("scroll", changeNavbarColor);
  }, []);

  return (
    <>
      <Head>
        <title>Golden Step</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon_io/favicon.ico" />
      </Head>
      {colorChange ? (
        <div className="fixed top-0 w-full bg-white shadow-xl z-[999]">
          <Navbar2 />
        </div>
      ) : (
        <div className="fixed top-0 w-full z-[999]">
          <Navbar />
        </div>
      )}
      <Hero />
      <Arrivals />
      <Footer />
    </>
  )
}
